apiVersion: v2
name: catalyst
description: Helm chart for Catalyst
type: application
version: '0.0.1'
appVersion: '0.0.1'

dependencies:
  - name: contour
    version: 19.4.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: contour.enabled

  - name: metrics-server
    version: 3.10.0
    repository: "https://kubernetes-sigs.github.io/metrics-server"
    condition: metricsServer.enabled
