---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway.controlplane.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway.controlplane.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gateway.controlplane.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gateway.controlplane.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io