# Code generated by tools/gen-region-tiers from pkg/regiontier/tiers.yaml. DO NOT EDIT.
#
# Catalyst "large" region on Azure: 3 x Standard_D8s_v5 (24 vCPU total),
# plus a GP_Standard_D8ds_v5 PostgreSQL Flexible Server (8 vCPU, 32 GiB RAM).
# The same footprint Diagrid provisions for a managed large region on the
# clouds it provisions on.
#
# This file sets the region SIZE only. Everything else - availability posture
# (postgresql_high_availability), backups, networking, peering, bastion - stays
# at the guide's own defaults, because those are operator decisions rather than
# part of the size. Merge these values into your terraform.tfvars, or pass both
# files to terraform directly:
#
#   cd terraform && terraform apply \
#     -var-file=terraform.tfvars -var-file=tiers/large.tfvars
#
# (The guide's Makefile takes a single TF_VAR_FILE, so
# "make apply TF_VAR_FILE=terraform/tiers/large.tfvars" would REPLACE your
# own variables rather than layer on them.)

node_instance_type    = "Standard_D8s_v5"
node_desired_capacity = 3
node_min_capacity     = 3

postgresql_instance_class    = "GP_Standard_D8ds_v5"
postgresql_allocated_storage = 128
