# Code generated by tools/gen-region-tiers from pkg/regiontier/tiers.yaml. DO NOT EDIT.
#
# Catalyst "small" region on Azure: 2 x Standard_D4s_v5 (8 vCPU total),
# plus a GP_Standard_D2ds_v5 PostgreSQL Flexible Server (2 vCPU, 8 GiB RAM).
# The same footprint Diagrid provisions for a managed small region on the
# clouds it provisions on.
#
# This file sets the region SIZE only. Everything else - availability posture
# (postgresql_high_availability), backups, networking, peering, bastion - stays
# at the guide's own defaults, because those are operator decisions rather than
# part of the size. Merge these values into your terraform.tfvars, or pass both
# files to terraform directly:
#
#   cd terraform && terraform apply \
#     -var-file=terraform.tfvars -var-file=tiers/small.tfvars
#
# (The guide's Makefile takes a single TF_VAR_FILE, so
# "make apply TF_VAR_FILE=terraform/tiers/small.tfvars" would REPLACE your
# own variables rather than layer on them.)

node_instance_type    = "Standard_D4s_v5"
node_desired_capacity = 2
node_min_capacity     = 2

postgresql_instance_class    = "GP_Standard_D2ds_v5"
postgresql_allocated_storage = 32
