# Code generated by tools/gen-region-tiers from pkg/regiontier/tiers.yaml. DO NOT EDIT.
#
# Catalyst "xlarge" region on Azure: 5 x Standard_D8s_v5 (40 vCPU total),
# plus a GP_Standard_D16ds_v5 PostgreSQL Flexible Server (16 vCPU, 64 GiB RAM).
# The same footprint Diagrid provisions for a managed xlarge region on the
# clouds it provisions on.
#
# This file sets the region SIZE only. Everything else - availability posture
# (postgresql_high_availability), backups, networking, peering, bastion - stays
# at the guide's own defaults, because those are operator decisions rather than
# part of the size. Merge these values into your terraform.tfvars, or pass both
# files to terraform directly:
#
#   cd terraform && terraform apply \
#     -var-file=terraform.tfvars -var-file=tiers/xlarge.tfvars
#
# (The guide's Makefile takes a single TF_VAR_FILE, so
# "make apply TF_VAR_FILE=terraform/tiers/xlarge.tfvars" would REPLACE your
# own variables rather than layer on them.)

node_instance_type    = "Standard_D8s_v5"
node_desired_capacity = 5
node_min_capacity     = 5

postgresql_instance_class    = "GP_Standard_D16ds_v5"
postgresql_allocated_storage = 256
