# Code generated by tools/gen-region-tiers from pkg/regiontier/tiers.yaml. DO NOT EDIT.
#
# Catalyst "large" region on AWS: 3 x c6i.2xlarge (24 vCPU total),
# plus a db.m6g.2xlarge PostgreSQL instance (8 vCPU, 32 GiB RAM).
# The same footprint Diagrid provisions for a managed large region.
#
# This file sets the region SIZE only. Everything else - availability posture
# (postgresql_multi_az), backups, networking, peering, bastion - stays at the
# guide's own defaults, because those are operator decisions rather than part
# of the size. Merge these values into your terraform.tfvars, or pass both
# files to terraform directly:
#
#   cd terraform && terraform apply \
#     -var-file=terraform.tfvars -var-file=tiers/large.tfvars
#
# (The guide's Makefile takes a single TF_VAR_FILE, so
# "make apply TF_VAR_FILE=terraform/tiers/large.tfvars" would REPLACE your
# own variables rather than layer on them.)

node_instance_type    = "c6i.2xlarge"
node_desired_capacity = 3
node_min_capacity     = 3
node_max_capacity     = 5

postgresql_instance_class        = "db.m6g.2xlarge"
postgresql_allocated_storage     = 100
postgresql_max_allocated_storage = 500
