# Code generated by tools/gen-region-tiers from pkg/regiontier/tiers.yaml. DO NOT EDIT.
#
# Catalyst "xlarge" region on AWS: 5 x c6i.2xlarge (40 vCPU total),
# plus a db.m6g.4xlarge PostgreSQL instance (16 vCPU, 64 GiB RAM).
# The same footprint Diagrid provisions for a managed xlarge region.
#
# This file sets the region SIZE only. Everything else - availability posture
# (postgresql_multi_az), backups, networking, peering, bastion - stays at the
# guide's own defaults, because those are operator decisions rather than part
# of the size. Merge these values into your terraform.tfvars, or pass both
# files to terraform directly:
#
#   cd terraform && terraform apply \
#     -var-file=terraform.tfvars -var-file=tiers/xlarge.tfvars
#
# (The guide's Makefile takes a single TF_VAR_FILE, so
# "make apply TF_VAR_FILE=terraform/tiers/xlarge.tfvars" would REPLACE your
# own variables rather than layer on them.)

node_instance_type    = "c6i.2xlarge"
node_desired_capacity = 5
node_min_capacity     = 5
node_max_capacity     = 7

postgresql_instance_class        = "db.m6g.4xlarge"
postgresql_allocated_storage     = 200
postgresql_max_allocated_storage = 1000
