apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.gateway.envoy.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "gateway.envoy.labels" .)) "overrides" .Values.gateway.envoy.merge.labels) | nindent 4 }}
spec:
  {{- if not .Values.gateway.envoy.autoscaling.enabled }}
  replicas: {{ if .Values.gateway.ha.enabled }}{{ .Values.gateway.ha.minReplicas }}{{ else }}{{ .Values.gateway.envoy.replicaCount }}{{ end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gateway.envoy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/controlplane-config: {{ include (print $.Template.BasePath "/gateway/configmap.yaml") . | sha256sum }}
        dapr.io/app-id: gateway
        dapr.io/config: catalyst
        {{- if and (not .Values.gateway.tls.existingSecret) (or .Values.gateway.tls.cert .Values.gateway.tls.key) }}
        checksum/tls-secret: {{ include (print $.Template.BasePath "/gateway/tls-secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "merge.maps" (dict "base" (include "gateway.envoy.selectorLabels" . | fromYaml) "overrides" .Values.gateway.envoy.merge.selectorLabels) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway.envoy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.envoy.podSecurityContext | nindent 8 }}
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.waitForDaprConfig.enabled .Values.gateway.controlplane.xds.mtls.enabled }}
      initContainers:
      {{- if .Values.global.waitForDaprConfig.enabled }}
        {{- include "catalyst.waitForDaprConfigInitContainer" (dict "configName" "catalyst" "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - name: identity-injector-init
          command:
            - ./identity-injector
          args:
            - --exit-on-success
          env:
            {{- include "gateway.identityInjector.env" (dict "appID" "gateway") | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image) }}
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- include "gateway.identityInjector.volumeMounts" . | nindent 12 }}
      {{- end }}
      {{- end }}
      containers:
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - name: identity-injector
          command:
            - ./identity-injector
          env:
            {{- include "gateway.identityInjector.env" (dict "appID" "gateway") | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image) }}
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- include "gateway.identityInjector.volumeMounts" . | nindent 12 }}
      {{- end }}
        - name: envoy
          securityContext:
            {{- toYaml .Values.gateway.envoy.securityContext | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.envoy.image "consolidated" nil "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.envoy.image "consolidated" nil "global" .Values.global.image) }}
          args:
            - "-c"
            - "/etc/envoy/bootstrap-envoy.yaml"
            - "--service-node"
            - "catalyst-gateway"
            - "--service-cluster"
            - "catalyst-gateway"
          resources:
            {{- toYaml .Values.gateway.envoy.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.envoy.service.targetPort }}
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            {{- if .Values.gateway.tls.enabled }}
            - name: wildcard-tls-certs
              mountPath: "/etc/ssl/certs"
              readOnly: true
            {{- end }}
            {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              readOnly: true
              subPath: ca.crt
            - mountPath: /var/run/secrets/dapr.io/sentrytoken
              name: dapr-identity-token
              readOnly: true
            {{- end }}
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        {{- if .Values.gateway.tls.enabled }}
        - name: wildcard-tls-certs
          secret:
            secretName: {{ include "gateway.tlsSecretName" . }}
        {{- end }}
        {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - configMap:
            defaultMode: 420
            name: ca-certificates-bundle
          name: trust-bundle
        - name: tls-certs
          emptyDir: {}
        - name: dapr-identity-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: dapr.io/sentry
                  expirationSeconds: 7200
                  path: token
        {{- end }}
      nodeSelector:
        {{- include "catalyst.nodeSelector" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.envoy) | nindent 8 }}
      affinity:
        {{- include "catalyst.affinity" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.envoy) | nindent 8 }}
      tolerations:
        {{- include "catalyst.tolerations" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.envoy) | nindent 8 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-gateway-controlplane
  annotations:
    {{- with .Values.gateway.controlplane.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "gateway.controlplane.labels" .)) "overrides" .Values.gateway.controlplane.merge.labels) | nindent 4 }}
spec:
  replicas: {{ if .Values.gateway.ha.enabled }}{{ .Values.gateway.ha.minReplicas }}{{ else }}{{ .Values.gateway.controlplane.replicaCount }}{{ end }}
  selector:
    matchLabels:
      {{- include "gateway.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        dapr.io/app-id: gateway-controlplane
        dapr.io/config: catalyst
        kubectl.kubernetes.io/default-container: catalyst-gateway-controlplane
      labels:
        {{- include "merge.maps" (dict "base" (include "gateway.controlplane.selectorLabels" . | fromYaml) "overrides" .Values.gateway.controlplane.merge.selectorLabels) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway.controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.controlplane.podSecurityContext | nindent 8 }}
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.waitForDaprConfig.enabled .Values.gateway.controlplane.xds.mtls.enabled }}
      initContainers:
      {{- if .Values.global.waitForDaprConfig.enabled }}
        {{- include "catalyst.waitForDaprConfigInitContainer" (dict "configName" "catalyst" "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - name: identity-injector-init
          command:
            - ./identity-injector
          args:
            - --exit-on-success
          env:
            {{- include "gateway.identityInjector.env" (dict "appID" "gateway-controlplane") | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image) }}
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- include "gateway.identityInjector.volumeMounts" . | nindent 12 }}
      {{- end }}
      {{- end }}
      containers:
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - name: identity-injector
          command:
            - ./identity-injector
          env:
            {{- include "gateway.identityInjector.env" (dict "appID" "gateway-controlplane") | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.identityInjector.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image) }}
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- include "gateway.identityInjector.volumeMounts" . | nindent 12 }}
      {{- end }}
        - name: catalyst-gateway-controlplane
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONFIG_FILE_DIR
              value: /etc/gateway-controlplane
            - name: LEADER_ELECTION_ENABLED
              value: {{ .Values.gateway.ha.enabled | quote }}
            - name: GATEWAY_TLS_ENABLED
              value: {{ .Values.gateway.tls.enabled | quote }}
          {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - name: XDS_SERVER_TLS_CERT
              value: "/var/run/secrets/diagrid.io/tls/tls.crt"
            - name: XDS_SERVER_TLS_KEY
              value: "/var/run/secrets/diagrid.io/tls/tls.key"
            - name: XDS_SERVER_CA_CERT
              value: "/var/run/secrets/diagrid.io/trust/ca.crt"
          {{- end }}
          {{- if and (eq .Values.global.secrets.provider "postgresql") .Values.global.secrets.postgresql.existingSecret }}
          {{- $pgSecret := .Values.global.secrets.postgresql.existingSecret }}
          {{- $pgKeys := .Values.global.secrets.postgresql.existingSecretKeys }}
            - name: SECRETS_POSTGRESQL_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.connection_string | default "connection_string" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_KEK_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.kek_provider | default "kek_provider" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_PRIMARY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.primary_encryption_key | default "primary_encryption_key" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_PRIMARY_KEY_VERSION
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.primary_key_version | default "primary_key_version" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_SECONDARY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.secondary_encryption_key | default "secondary_encryption_key" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_SECONDARY_KEY_VERSION
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.secondary_key_version | default "secondary_key_version" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_AWS_KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.aws_kms_key_id | default "aws_kms_key_id" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.aws_region | default "aws_region" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.aws_access_key | default "aws_access_key" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.aws_secret_access_key | default "aws_secret_access_key" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_USE_AWS_IAM
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.use_aws_iam | default "use_aws_iam" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_AWS_ASSUME_ROLE_ARN
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.aws_assume_role_arn | default "aws_assume_role_arn" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_MAX_CONNS
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.max_conns | default "max_conns" }}
                  optional: true
            - name: SECRETS_POSTGRESQL_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: {{ $pgSecret }}
                  key: {{ $pgKeys.timeout | default "timeout" }}
                  optional: true
          {{- end }}
          securityContext:
            {{- toYaml .Values.gateway.controlplane.securityContext | nindent 12 }}
          image: {{ include "catalyst.image" (dict "image" .Values.gateway.controlplane.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image "context" .) }}
          imagePullPolicy: {{ include "catalyst.imagePullPolicy" (dict "image" .Values.gateway.controlplane.image "consolidated" .Values.global.consolidated_image "global" .Values.global.image) }}
          command: ["./gateway-controlplane"]
          resources:
            {{- toYaml .Values.gateway.controlplane.resources | nindent 12 }}
          ports:
            - name: httphealthcheck
              containerPort: {{ .Values.gateway.controlplane.deployment.httpHealthCheck.containerPort }}
              protocol: TCP
            - name: http-xds
              containerPort: {{ .Values.gateway.controlplane.deployment.httpXDS.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: gateway-controlplane-config
              mountPath: /etc/gateway-controlplane
            - mountPath: /var/run/secrets/dapr.io/sentrytoken
              name: dapr-identity-token
              readOnly: true
          {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              subPath: ca.crt
          {{- end }}
      volumes:
        - name: gateway-controlplane-config
          configMap:
            name: catalyst-gateway-controlplane-config
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - configMap:
            defaultMode: 420
            name: ca-certificates-bundle
          name: trust-bundle
        - emptyDir: {}
          name: tls-certs
        - name: dapr-identity-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: dapr.io/sentry
                  expirationSeconds: 7200
                  path: token
      {{- end }}
      nodeSelector:
        {{- include "catalyst.nodeSelector" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.controlplane) | nindent 8 }}
      affinity:
        {{- include "catalyst.affinity" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.controlplane) | nindent 8 }}
      tolerations:
        {{- include "catalyst.tolerations" (dict "shared" .Values.shared.scheduling "component" .Values.gateway.controlplane) | nindent 8 }}
