{{- if .Values.gateway.envoy.autoscaling.enabled }}
{{- with .Values.gateway.envoy.autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalyst-gateway
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "gateway.envoy.labels" $)) "overrides" $.Values.gateway.envoy.merge.labels) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalyst-gateway
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  {{- with .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
