{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp.serviceAccountName" . }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mcp.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
